config/routes.rb
Rails.application.routes.draw do

  root :to => "cards#index"
  
  resources :cards do
    collection do
      put 'remove'
    end
  end
  
  resources :accounts do
    collection do
      get 'options'
      get 'withdraw'
      get 'deposit'
      get 'account'
      post 'transaction'
    end
  end
  
  
  resources :identities, only: [:index] do
    collection do
      get 'sign_up'
      get 'login'
      get 'authorisation'
      put 'logout'
    end
  end
  
  
end

app/models/user_proxy.rb
class UserProxy
  
  include Wisper::Publisher
  
  include Mongoid::Document
  include Mongoid::Timestamps  
  
  field :name, type: String
  field :email, type: String
  field :email_verified, type: Boolean
  field :access_token, type: Hash
  field :id_token, type: Hash
  
  #belongs_to :kiwi
  
  def self.set_up_user(access_token: nil, id_token: nil)
    user = get_user_from_id_service(access_token: access_token)
    proxy = self.find_or_create(id_token: id_token, access_token: access_token)
    proxy
  end
  
  def self.find_or_create(id_token: nil, access_token: nil)
    up = self.where(name: id_token["preferred_username"]).first
    if up
      up.add_attrs(id_token: id_token, access_token: access_token)
    else
      up = self.new.add_attrs(id_token: id_token, access_token: access_token)
    end
    up
  end
    
  def self.get_user_from_id_service(access_token: nil)
    conn = Faraday.new(url: Setting.oauth["id_userinfo_service_url"])    
    conn.params = {access_code: access_token["access_code"]} 
    conn.authorization :Bearer, access_token["access_code"]
    resp = conn.get
    raise if resp.status >= 300
    JSON.parse(resp.body)
  end
    
  
  def add_attrs(id_token: nil, access_token: nil)
    raise if !id_token
    name = "preferred_username"
    email = "email_verified"
    key = :id_token
    self.name = id_token["preferred_username"]
    self.email_verified = id_token["email_verified"]
    self.email = id_token["email"]    
    self.access_token = access_token
    self.id_token = id_token
    save
    self
  end
    
  def requires_a_kiwi?
    if Setting.oauth(:require_additional_identity)
      true
    else
      false
    end
  end
  
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  
  def index
    @accounts = AccountsManager.all(user_proxy: @current_user_proxy)
  end
  
  def account
    @link = params[:link]
    @account = AccountsManager.new.get_account(user_proxy: @current_user_proxy, link: @link)
  end
  
  def options
    @deposit = params[:deposit]
    @withdraw = params[:withdraw]
    @self = params[:self]
    @type = params[:type]
  end
  
  def withdraw
    @link = params[:link]
  end
  
  def deposit
    @link = params[:link]
  end
    
  #{"utf8"=>"✓", "authenticity_token"=>"fMD60zZkE0aX1nSbU6B0OH22AWd92JoSIVJW/sh0f8Q=", "amount"=>"10", "commit"=>"Submit", "link"=>"http://localhost:3023/api/v1/accounts/546569bf4d617414e60d0000/transactions/deposit"}
  def transaction
    acct_mgr = AccountsManager.new
    acct_mgr.subscribe self
    acct_mgr.process_account_transaction(link: params[:link], amount: params[:amount], user_proxy: @current_user_proxy)
  end
  
  def succesful_transaction_event(acct_mgr)
    flash.notice = "Well Done!!"
    redirect_to accounts_path
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user_proxy
  
  before_filter :current_user_proxy
  
  
  def current_user_proxy
    @current_user_proxy ||= UserProxy.find(session[:user_proxy]["proxy_id"]) if session[:user_proxy]
    if Setting.oauth(:require_additional_identity)
      @kiwi = @current_user_proxy.kiwi if @current_user_proxy
    end
  end
  
  
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  
  def index
  end
  
  def remove
    session[:user_proxy] = nil
    redirect_to cards_path
  end
  
end

app/controllers/identities_controller.rb
class IdentitiesController < ApplicationController
  
  def sign_up
    # Send the Signup to the ID Service via a OAuth Redirect
    auth_service = IdentityAdapter.new.authorise_url(host: request.host_with_port, scope: "signup")
    redirect_to auth_service
  end
  
  def login
    # Send the Login to the ID Service via a OAuth Redirect
    auth_service = IdentityAdapter.new.authorise_url(host: request.host_with_port, scope: "atm")
    redirect_to auth_service
  end
  
  def authorisation
    # Get an access token for the logged_in user from the ID Service using an OAuth /token call
    # Now we need to create an internal "user" by getting the /me
    auth = IdentityAdapter.new
    auth.subscribe(self)
    auth.get_access(params: params, host: request.host_with_port)
  end
  
  def logout
    auth_logout_service = IdentityAdapter.new.logout_url(user_proxy: @current_user_proxy, host: request.host_with_port)
    session[:user_proxy] = nil
    redirect_to auth_logout_service
  end
  
  def valid_authorisation(user_proxy)
    session[:user_proxy] = {proxy_id: user_proxy.id.to_s, expires: 10.minutes.from_now}
    redirect_to accounts_path
  end

  def create_a_kiwi(user_proxy)
    session[:user_proxy] = {proxy_id: user_proxy.id.to_s, expires: 10.minutes.from_now}    
    redirect_to new_kiwi_path(scope: :sign_up)
  end
  
  def login_error
    flash.now.alert = "Invalid Login"
    render 'shared/login_error'
    
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/_account_balance.html.erb
<dl class="sub-nav">
  <dt>Balance:</dt>
  <dd class="active"><a href="#"><%= @account.account["balance"] %></a></dd>
</dl>

app/views/accounts/_amount_form.html.erb
<%= form_tag(transaction_accounts_path(link: @link), html: { class: "custom"}) do %>
   <div class="row">
     <div class="small-2 columns">
       <%= label_tag "#{action} amount", nil, class: "right inline" %>
     </div>
     <div class="small-6 columns end">
       <%= number_field_tag :amount %>
     </div> 
   </div>
   <div class="row">
     <div class="small-4 small-offset-4 columns">
       <%= submit_tag 'Submit', :class => 'button small' %>
     </div>
   </div>
<% end %>

app/views/accounts/_options.html.erb
<div class="row">
   <div class="icon-bar large-vertical three-up">
      <%= link_to(deposit_accounts_path(link: @deposit,class: "item"), class: "item", remote: true) do %>
          <i class="fi-plus"></i>
          <label><%= @type %> Deposit</label>
      <% end %>
      <%= link_to(withdraw_accounts_path(link: @withdraw,class: "item"), class: "item", remote: true) do %>
          <i class="fi-minus"></i>
          <label><%= @type %> Withdraw</label>
      <% end %>   
      <%= link_to(account_accounts_path(link: @self, class: "item"), class: "item", remote: true) do %>
          <i class="fi-dollar"></i>
          <label><%= @type %> Balance</label>
      <% end %>         
   </div>
</div>

app/views/accounts/index.html.erb
<div class="row">
   <div class="small-2 columns">

         <div class="icon-bar large-vertical three-up">
            <% @accounts.each  do |acct|%>
               <%= link_to(options_accounts_path(deposit: acct.link_for(rel: "transaction_deposit"),
                                                withdraw: acct.link_for(rel: "transaction_withdraw"),
                                                self: acct.link_for(rel: "self"),
                                                type: acct.account_msg["type"]), 
                                                class: "item", remote: true) do %>
                   <i class="fi-dollar"></i>
                   <label><%= acct.account_msg["type"]%></label>
                <% end %>
         <% end %>
      </div>
   </div>
   <div class="small-2 columns">
      <div id="account"></div>
   </div>
   <div class="small-8 columns">
      <div id="account_content"></div>
   </div>
</div>
<div class="row">
   <div class="small-3 small-centered columns">
      <%= link_to 'Remove Card', remove_cards_path, method: :put, class: "button"%>
   </div>
</div>

app/views/cards/index.html.erb
<div class="row">
  <div class="small-3 small-centered columns">
     <%= link_to "Insert Card", login_identities_path, class: "button expand"%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "ATM" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="row">
      <div class="small-3 small-centered columns">
        <%= render partial: 'shared/flash', locals: {flashs: flash}%>
      </div>
    </div>
    <div class="row">
      <div class="small-10 small-centered columns">    
        <div class="panel">
          <%= yield %>
        </div>
      </div>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/shared/_flash.html.erb
<%if flashs %>
		<% flashs.each do |key, msg| %>
         <div data-alert class="alert-box success radius">
            <%= "#{key}: #{msg}"%>
           <a href="#" class="close">&times;</a>
         </div>
		<% end %>
<% end %>

app/views/shared/login_error.html.erb
<%= render partial: 'shared/flash', locals: {flashs: flash}%>